CREATE TABLE REVIEW (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  body VARCHAR(10000) NULL,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL,
  product_id INT NOT NULL
);

CREATE TABLE PRODUCT (
  id INT AUTO_INCREMENT primary key,
  name VARCHAR(255) NOT NULL,
  price INT NOT NULL,
  description VARCHAR(100) NOT NULL
);

CREATE TABLE COMMENT (
  id INT AUTO_INCREMENT primary key,
  title VARCHAR(255) NOT NULL,
  body VARCHAR(10000) NULL,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL,
  review_id INT NOT NULL
);


ALTER TABLE REVIEW ADD CONSTRAINT review_product_id_fk FOREIGN KEY (product_id) REFERENCES PRODUCT (id);

ALTER TABLE COMMENT ADD CONSTRAINT comment_review_id_fk FOREIGN KEY (review_id) REFERENCES REVIEW (id);